apiVersion: v1
kind: Service
metadata:
  name: ai-assignment-app-service
spec:
  selector:
    app: ai-assignment-app
  ports:
    - protocol: TCP
      port: 80  # The port to access the service from outside
      targetPort: 5000  # The port on the container that the service should route to
  type: LoadBalancer  # Exposes the service outside of the cluster
